apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    # Enforce Pod Security Standards (Restricted)
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
    # Baseline for application workloads
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
